# Generated by Django 4.1.1 on 2022-09-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_curso_entregable_estudiante_profesor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregable',
            old_name='fechaDeEntrega',
            new_name='fecha_de_entrega',
        ),
        migrations.AddField(
            model_name='entregable',
            name='entregado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
